spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    # 처음엔 jdbc:h2:~/jpashop 로 접속하여 ~/jpashop.mv.db 파일 생성을 확인한다. 그 후 해당 url로 접속할 수 있다.
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        # 시스템 아웃으로 로그를 찍기 떄문에 주석처리 한다. 이 옵션 대신 org.hibernate.SQL 로 확인할 수 있다.
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
